name: GetMeHome
version: 3.0.0
author: Simon Chuu
contributors: [wangzhizhou]
description: Simple home plugin that just gets you home
main: com.simonorj.mc.getmehome.GetMeHome
website: http://github.com/SimonOrJ/GetMeHome
api-version: 1.21.7

commands:
  getmehome:
    description: GetMeHome's main (help) command
    usage: /getmehome
  delhome:
    description: Deletes a set home
    usage: /delhome [home name]
    permission: getmehome.command.delhome
  home:
    aliases: [ h ]
    description: Sends you home
    usage: /home [home name]
    permission: getmehome.command.home
  listhomes:
    aliases: [ homes ]
    description: Lists all the homes
    usage: /listhomes
    permission: getmehome.command.listhomes
  sethome:
    description: Sets home at your current position
    usage: /sethome [home name]
    permission: getmehome.command.sethome
  setdefaulthome:
    description: Sets a different home name as the default home.
    usage: /setdefaulthome <home name>
    permission: getmehome.command.setdefaulthome

permissions:
  # bStats
  bstats:
    default: true
    description: Allows bStats to collect plugin metrics

  # Reload
  getmehome.reload:
    description: Allows /getmehome reload
    default: op

  # Options
  getmehome.delay.instantother:
    description: No delay for /home to other player's home
    default: op
  getmehome.delay.allowmove:
    description: Allows moving while waiting for /home warmup
    default: false

  # User
  getmehome.user:
    description: Allows the user-level usage of home commands
    default: true
    children:
      getmehome.command.delhome: true
      getmehome.command.home: true
      getmehome.command.listhomes: true
      getmehome.command.sethome: true
      getmehome.command.setdefaulthome: true

  # Commands
  getmehome.command.delhome:
    description: Allows /delhome
  getmehome.command.delhome.other:
    description: Allows `/delhome <player> <name>` to delete other player's home
    default: op
    children:
      getmehome.command.delhome: true
  getmehome.command.home:
    description: Allows /home
  getmehome.command.home.other:
    description: Allows `/home <player> <home>` to teleport to other user's homes
    default: op
    children:
      getmehome.command.home: true
  getmehome.command.listhomes:
    description: Allows /listhomes
  getmehome.command.listhomes.other:
    description: Allows `/listhomes <player>` (as opposed to just /listhomes)
    default: op
    children:
      getmehome.command.listhomes: true
  getmehome.command.sethome:
    description: Allows /sethome
  getmehome.command.sethome.other:
    description: Allows `/sethome <player> <name>` to set other player's home
    default: op
    children:
      getmehome.command.sethome: true
  getmehome.command.setdefaulthome:
    description: Allows /setdefaulthome
